openapi: 3.0.0
info:
  title: LogisticRegression
  description: "Sklearn LogisticRegression"
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080/cloudmesh
    description: "Sklearn LogisticRegression"
paths:
  /LogisticRegression/fit:
     get:
      summary: "Fit the model according to the given training data."
      description: "None (Optional extended description in CommonMark or HTML)"
      operationId: LogisticRegression.fit
      parameters:
        - in: query
          name: X
          description: "Training vector, where n_samples is the number of samples and
                       n_features is the number of features."
          schema:
            $ref: '#/components/schemas/ArrayOfNumber'
        - in: query
          name: y
          description: "Target vector relative to X."
          schema:
            $ref: '#/components/schemas/ArrayOfNumber'
        - in: query
          name: sample_weight
          description: "Array of weights that are assigned to individual samples.
                       If not provided, then each sample is given unit weight.

                       .. versionadded:: 0.17
                          *sample_weight* support to LogisticRegression."
          schema:
            $ref: '#/components/schemas/ArrayOfNumber'
        - in: query
          name: X_shape_x
          description: "Array of weights that are assigned to individual samples.
                       If not provided, then each sample is given unit weight.

                       .. versionadded:: 0.17
                          *sample_weight* support to LogisticRegression."
          schema:
            type: integer
        - in: query
          name: X_shape_y
          description: "Array of weights that are assigned to individual samples.
                       If not provided, then each sample is given unit weight.

                       .. versionadded:: 0.17
                          *sample_weight* support to LogisticRegression."
          schema:
            type: integer
      responses:
        '200':
          description: "OK"
          content:
            text/plain:
              schema:
                type: integer


components:
  schemas:
    ArrayOfNumber:
      type: array
      items:
        type: number

    ArrayOfAny:
      type: array
      items: {}

    ArrayOfOneInList:
      type: array
      items:
        oneOf:
          - type: string
          - type: integer
